/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dropnumbergame;

import javax.swing.JLabel;

/**
 *
 * @author asus
 */
public class GameSımulator extends javax.swing.JFrame {

    boolean isMergeAnimationRunning = false;
    int columnBeingMerged = -1;
    javax.swing.Timer mergeAnimationTimer;
    JLabel[][] cells;
    MultiLinkedList grid = new MultiLinkedList();
    int step = 0;

    int[][] moves = {
        {2, 0}, {2, 3}, {4, 1}, {2, 2}, {4, 4},
        {2, 1}, {4, 4}, {8, 0}, {8, 0},
        {32, 1}, {2, 2}, {64, 2}, {16, 3},
        {64, 1}, {32, 2}, {16, 0}, {16, 4}, {32, 2},
        {64, 1}, {8, 3}, {4, 3},
        {2, 3}, {2, 3}, {2, 1}, {64, 2}, {32, 2}, {16, 2}, {8, 2},
        {8, 2}, {4, 1}, {8, 1}
    };

    private java.awt.Color getTileColor(int value) {

        switch (value) {
            case 2:
                return new java.awt.Color(230, 210, 255); 
            case 4:
                return new java.awt.Color(200, 230, 255);
            case 8:
                return new java.awt.Color(210, 255, 210); 
            case 16:
                return new java.awt.Color(255, 220, 180); 
            case 32:
                return new java.awt.Color(255, 200, 220); 
            case 64:
                return new java.awt.Color(220, 210, 255); 
            case 128:
                return new java.awt.Color(200, 255, 255); 
            case 256:
                return new java.awt.Color(255, 240, 200);
            default:
                return java.awt.Color.LIGHT_GRAY;
        }
    }

    /**
     * Creates new form GameSımulator
     */
    public GameSımulator() {
        initComponents();

        this.cells = new JLabel[][]{
            {cell00, cell01, cell02, cell03, cell04},
            {cell10, cell11, cell12, cell13, cell14},
            {cell20, cell21, cell22, cell23, cell24},
            {cell30, cell31, cell32, cell33, cell34},
            {cell40, cell41, cell42, cell43, cell44},
            {cell50, cell51, cell52, cell53, cell54},
            {cell60, cell61, cell62, cell63, cell64}
        };

        for (int row = 0; row < 7; row++) {
            for (int col = 0; col < 5; col++) {
                cells[row][col].setOpaque(true);
            }
        }
    }
    // Updates the GUI cells according to the current multi-linked list state

    public void updateGrid() {
        for (int row = 0; row < 7; row++) {
            for (int col = 0; col < 5; col++) {

                Node node = grid.findNode(row, col);

                cells[row][col].setOpaque(true);

                if (node != null) {
                    cells[row][col].setText(String.valueOf(node.value));
                    cells[row][col].setBackground(getTileColor(node.value));
                } else {
                    cells[row][col].setText(".");
                    cells[row][col].setBackground(java.awt.Color.WHITE);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nextbutton = new javax.swing.JButton();
        stepLabel = new javax.swing.JLabel();
        cell30 = new javax.swing.JLabel();
        cell21 = new javax.swing.JLabel();
        cell41 = new javax.swing.JLabel();
        cell40 = new javax.swing.JLabel();
        cell50 = new javax.swing.JLabel();
        cell02 = new javax.swing.JLabel();
        cell11 = new javax.swing.JLabel();
        cell20 = new javax.swing.JLabel();
        cell33 = new javax.swing.JLabel();
        cell60 = new javax.swing.JLabel();
        cell10 = new javax.swing.JLabel();
        cell51 = new javax.swing.JLabel();
        cell52 = new javax.swing.JLabel();
        cell31 = new javax.swing.JLabel();
        cell61 = new javax.swing.JLabel();
        cell12 = new javax.swing.JLabel();
        cell01 = new javax.swing.JLabel();
        cell42 = new javax.swing.JLabel();
        cell32 = new javax.swing.JLabel();
        cell22 = new javax.swing.JLabel();
        cell23 = new javax.swing.JLabel();
        cell63 = new javax.swing.JLabel();
        cell14 = new javax.swing.JLabel();
        cell13 = new javax.swing.JLabel();
        cell44 = new javax.swing.JLabel();
        cell62 = new javax.swing.JLabel();
        cell64 = new javax.swing.JLabel();
        cell24 = new javax.swing.JLabel();
        cell43 = new javax.swing.JLabel();
        cell53 = new javax.swing.JLabel();
        cell04 = new javax.swing.JLabel();
        cell34 = new javax.swing.JLabel();
        cell03 = new javax.swing.JLabel();
        cell54 = new javax.swing.JLabel();
        cell00 = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("   Drop Number Game");

        nextbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nextbutton.setText("NEXT STEP");
        nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonActionPerformed(evt);
            }
        });

        stepLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stepLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stepLabel.setText("STEP :   0");

        cell30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell30.setText(".");
        cell30.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell21.setText(".");
        cell21.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell41.setText(".");
        cell41.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell40.setText(".");
        cell40.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell50.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell50.setText(".");
        cell50.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell02.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell02.setText(".");
        cell02.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell11.setText(".");
        cell11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell20.setText(".");
        cell20.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell33.setText(".");
        cell33.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell60.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell60.setText(".");
        cell60.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell10.setText(".");
        cell10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell51.setText(".");
        cell51.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell52.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell52.setText(".");
        cell52.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell31.setText(".");
        cell31.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell61.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell61.setText(".");
        cell61.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell12.setText(".");
        cell12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell01.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell01.setText(".");
        cell01.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell42.setText(".");
        cell42.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell32.setText(".");
        cell32.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell22.setText(".");
        cell22.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell23.setText(".");
        cell23.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell63.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell63.setText(".");
        cell63.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell14.setText(".");
        cell14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell13.setText(".");
        cell13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell44.setText(".");
        cell44.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell62.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell62.setText(".");
        cell62.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell64.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell64.setText(".");
        cell64.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell24.setText(".");
        cell24.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell43.setText(".");
        cell43.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell53.setText(".");
        cell53.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell04.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell04.setText(".");
        cell04.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell34.setText(".");
        cell34.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell03.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell03.setText(".");
        cell03.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell54.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell54.setText(".");
        cell54.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cell00.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cell00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell00.setText(".");
        cell00.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cell00.setOpaque(true);

        infoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("Scenario information will appear here.");

        resetButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(nextbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cell20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(cell10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(cell40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(cell60, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(cell30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(cell00, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(cell50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                    .addGap(5, 5, 5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cell11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cell21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cell24, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cell01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cell41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cell43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell44, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cell31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(cell33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cell34, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cell51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(5, 5, 5)
                                                    .addComponent(cell52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(5, 5, 5)
                                                    .addComponent(cell53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cell61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(5, 5, 5)
                                                    .addComponent(cell62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(5, 5, 5)
                                                    .addComponent(cell63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cell54, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                                .addComponent(cell64, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(165, 165, 165)
                                            .addComponent(stepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cell00, cell01, cell02, cell03, cell04, cell10, cell11, cell12, cell13, cell14, cell20, cell21, cell22, cell23, cell24, cell30, cell31, cell32, cell33, cell34, cell40, cell41, cell42, cell43, cell44, cell50, cell51, cell52, cell53, cell54, cell60, cell61, cell62, cell63, cell64});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cell00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cell02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cell01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cell03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cell04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell60, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(nextbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(stepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cell00, cell01, cell02, cell03, cell04, cell10, cell11, cell12, cell13, cell14, cell20, cell21, cell22, cell23, cell24, cell30, cell31, cell32, cell33, cell34, cell40, cell41, cell42, cell43, cell44, cell50, cell51, cell52, cell53, cell54, cell60, cell61, cell62, cell63, cell64});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonActionPerformed
        if (isMergeAnimationRunning) {
            return;
        }

        if (step < moves.length) {
 /*
             * Get the current move.
             * moves[step][0] is the tile value.
             * moves[step][1] is the target column.
             */
            int tileValue = moves[step][0];
            int targetColumn = moves[step][1];
            infoLabel.setText("STEP " + (step + 1) + " - Tile " + tileValue
                    + " will be dropped into column " + targetColumn + ".");
       
            if (grid.getColumnSize(targetColumn) == 7) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Game Over! Column " + targetColumn + " is full.",
                        "Drop Number Game",
                        javax.swing.JOptionPane.WARNING_MESSAGE
                );
                nextbutton.setEnabled(false);
                return;
            }
            // Add the tile first, then show merge operations step by step
            grid.addTileOnly(targetColumn, tileValue);

            step++;
            stepLabel.setText("STEP : " + step);

            updateGrid();

            // Start merge animation for the selected column
            isMergeAnimationRunning = true;
            columnBeingMerged = targetColumn;

            nextbutton.setEnabled(false);

            mergeAnimationTimer = new javax.swing.Timer(800, e -> {

                boolean didMergeHappen = grid.mergeOneStep(columnBeingMerged);

                updateGrid();
                //If no merge is left, stop animation and enable the button again
                
                if (!didMergeHappen) {
                    mergeAnimationTimer.stop();
                    isMergeAnimationRunning = false;
                    nextbutton.setEnabled(true);

                   // If all scenario steps are finished, show game over message
                    if (step >= moves.length) {
                        javax.swing.JOptionPane.showMessageDialog(
                                this,
                                "Game Over! Scenario finished.",
                                "Drop Number Game",
                                javax.swing.JOptionPane.INFORMATION_MESSAGE
                        );
                        nextbutton.setEnabled(false);
                    }
                }
            });

            mergeAnimationTimer.setInitialDelay(1200);
            mergeAnimationTimer.start();
        }
    }
    
        // Resets the game board and restarts the scenario from the beginning
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        
        // Stop merge animation if it is currently running
        if (mergeAnimationTimer != null && mergeAnimationTimer.isRunning()) {
            mergeAnimationTimer.stop();
        }
        // Clear animation state
        isMergeAnimationRunning = false;
        columnBeingMerged = -1;
        
        // Create a new empty multi-linked list and reset step counter
        grid = new MultiLinkedList();
        step = 0;

        // Reset GUI labels
        stepLabel.setText("STEP : 0");
        infoLabel.setText("Scenario information will appear here.");

        nextbutton.setEnabled(true);

         // Refresh the board visually
        updateGrid();
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSımulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSımulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSımulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSımulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameSımulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cell00;
    private javax.swing.JLabel cell01;
    private javax.swing.JLabel cell02;
    private javax.swing.JLabel cell03;
    private javax.swing.JLabel cell04;
    private javax.swing.JLabel cell10;
    private javax.swing.JLabel cell11;
    private javax.swing.JLabel cell12;
    private javax.swing.JLabel cell13;
    private javax.swing.JLabel cell14;
    private javax.swing.JLabel cell20;
    private javax.swing.JLabel cell21;
    private javax.swing.JLabel cell22;
    private javax.swing.JLabel cell23;
    private javax.swing.JLabel cell24;
    private javax.swing.JLabel cell30;
    private javax.swing.JLabel cell31;
    private javax.swing.JLabel cell32;
    private javax.swing.JLabel cell33;
    private javax.swing.JLabel cell34;
    private javax.swing.JLabel cell40;
    private javax.swing.JLabel cell41;
    private javax.swing.JLabel cell42;
    private javax.swing.JLabel cell43;
    private javax.swing.JLabel cell44;
    private javax.swing.JLabel cell50;
    private javax.swing.JLabel cell51;
    private javax.swing.JLabel cell52;
    private javax.swing.JLabel cell53;
    private javax.swing.JLabel cell54;
    private javax.swing.JLabel cell60;
    private javax.swing.JLabel cell61;
    private javax.swing.JLabel cell62;
    private javax.swing.JLabel cell63;
    private javax.swing.JLabel cell64;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextbutton;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel stepLabel;
    // End of variables declaration//GEN-END:variables
}
